FROM cytopia/ansible:latest-tools as build

# Metadata params
ARG BUILD_DATE
ARG VCS_REF
ARG TIMEZONE
ARG LANG="C.UTF-8"

LABEL maintainer="Asapdotid <asapdotid@gmail.com>" \
    org.label-schema.url="https://gitlab.com/asap-labs/docker-ansible/-/blob/main/README.md" \
    org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.vcs-url="https://gitlab.com/asap-labs/docker-ansible.git" \
    org.label-schema.vcs-ref=${VCS_REF} \
    org.label-schema.docker.dockerfile="/${DOCKER_FILE}" \
    org.label-schema.description="Ansible docker image" \
    org.label-schema.schema-version="tools"

# # Define uid/gid and user/group names
ENV \
	MY_USER=ansible \
	MY_GROUP=ansible \
	MY_UID=1000 \
	MY_GID=1000

RUN apk --update --no-cache add \
    ca-certificates \
    openssh-client \
    openssl \
    rsync \
    sed \
    gawk \
    curl \
    perl-mime-base64 \
    sshpass

ENV TZ=${TIMEZONE}
RUN apk add tzdata \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo '$TZ' > /etc/timezone \
    && apk del tzdata

RUN rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*

RUN mkdir -p /etc/ansible \
    && echo 'localhost' > /etc/ansible/hosts \
    && echo -e """\
\n\
Host *\n\
    StrictHostKeyChecking no\n\
    UserKnownHostsFile=/dev/null\n\
    LogLevel ERROR\n\
""" >> /etc/ssh/ssh_config

COPY ./requirements.yml ./
RUN ansible-galaxy install -r requirements.yml

COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN ["chmod", "+x", "/docker-entrypoint.sh"]

WORKDIR /data
ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["ansible", "--version"]