#!/bin/sh
set -o nounset -o errexit

ALPINE_VERSION=3.17
ANSIBLE_VERSION=7.1.0
DOCKER_FILE=Dockerfile
DOCKER_REPO=asapdotid
IMAGE_NAME=ansible
IMAGE_VERSION=tools

# Check first if docker image is exist
OLD="$(docker ps --all --quiet --filter=name=$DOCKER_REPO/$IMAGE_NAME:$IMAGE_VERSION)"
if [ -n "$OLD" ]; then
    exec docker stop $OLD && docker rm $OLD
fi

# Run Build Docker Image
exec docker build \
    --build-arg VCS_REF=$(git rev-parse --short HEAD) \
    --build-arg BUILD_DATE=$(date -u +”%Y-%m-%dT%H:%M:%SZ”) \
    --build-arg ALPINE_VERSION=$ALPINE_VERSION \
    --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION \
    -f $DOCKER_FILE \
    -t $DOCKER_REPO/$IMAGE_NAME:$IMAGE_VERSION .
